function escJsTemplate(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/\x1b/g, '\\x1b')
    .replace(/\r/g, '\\r');
}

function escPython(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"\\"\\"')
    .replace(/\x1b/g, '\\x1b');
}

function escPhp(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\x1b/g, '\\e');
}

function escGo(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\x1b/g, '\\x1b')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function escRust(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\x1b/g, '\\x1b')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function escRuby(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/#/g, '\\#')
    .replace(/\x1b/g, '\\e');
}

function escBash(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\x1b/g, '\\e');
}

function escJava(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\x1b/g, '\\u001b')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function escCSharp(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\x1b/g, '\\u001b')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

// generate
function genJs(banner, varName) {
  const lit = escGo(banner); 
  return `// Generated by banner-cli
const ${varName} = "${lit}";

console.log(${varName});

export default ${varName};
`;
}

function genTs(banner, varName) {
  const lit = escGo(banner);
  return `// Generated by banner-cli
const ${varName}: string = "${lit}";

console.log(${varName});

export default ${varName};
`;
}

function genPython(banner, varName) {
  const lit = escPython(banner);
  return `# Generated by banner-cli
${varName} = """${lit}"""

if __name__ == "__main__":
    print(${varName})
`;
}

function genPhp(banner, varName) {
  const lit = escPhp(banner);
  return `<?php
// Generated by banner-cli
$${varName} = "${lit}";

echo $${varName} . PHP_EOL;
`;
}

function genGo(banner, varName) {
  const lit = escGo(banner);
  return `// Generated by banner-cli
package main

import "fmt"

const ${varName} = "${lit}"

func main() {
\tfmt.Println(${varName})
}
`;
}

function genRust(banner, varName) {
  const lit = escRust(banner);
  return `// Generated by banner-cli
const ${varName.toUpperCase()}: &str = "${lit}";

fn main() {
    println!("{}", ${varName.toUpperCase()});
}
`;
}

function genRuby(banner, varName) {
  const lit = escRuby(banner);
  return `# Generated by banner-cli
${varName.toUpperCase()} = "${lit}"

puts ${varName.toUpperCase()}
`;
}

function genBash(banner, varName) {
  const lit = escBash(banner);
  return `#!/usr/bin/env bash
# Generated by banner-cli
${varName.toUpperCase()}=$'${lit}'

printf '%s\\n' "$${varName.toUpperCase()}"
`;
}

function genJava(banner, varName) {
  const lit = escJava(banner);
  const className = 'Banner';
  return `// Generated by banner-cli
public class ${className} {
    public static final String ${varName.toUpperCase()} = "${lit}";

    public static void main(String[] args) {
        System.out.println(${varName.toUpperCase()});
    }
}
`;
}

function genCSharp(banner, varName) {
  const lit = escCSharp(banner);
  return `// Generated by banner-cli
using System;

public static class Banner
{
    public const string ${varName.charAt(0).toUpperCase() + varName.slice(1)} = "${lit}";

    public static void Main()
    {
        Console.WriteLine(${varName.charAt(0).toUpperCase() + varName.slice(1)});
    }
}
`;
}

export const LANGUAGES = {
  javascript: { label: 'JavaScript (ESM)', ext: 'js', gen: genJs },
  typescript: { label: 'TypeScript', ext: 'ts', gen: genTs },
  python: { label: 'Python', ext: 'py', gen: genPython },
  php: { label: 'PHP', ext: 'php', gen: genPhp },
  go: { label: 'Go', ext: 'go', gen: genGo },
  rust: { label: 'Rust', ext: 'rs', gen: genRust },
  ruby: { label: 'Ruby', ext: 'rb', gen: genRuby },
  bash: { label: 'Bash / Shell', ext: 'sh', gen: genBash },
  java: { label: 'Java', ext: 'java', gen: genJava },
  csharp: { label: 'C#', ext: 'cs', gen: genCSharp },
};

export function listLanguages() {
  return Object.entries(LANGUAGES).map(([key, v]) => ({ value: key, label: v.label }));
}

export function generateCode(language, banner, varName = 'banner') {
  const lang = LANGUAGES[language];
  if (!lang) throw new Error(`Unsupported language: ${language}`);
  const code = lang.gen(banner, varName);
  return { code, ext: lang.ext };
}

void escEscape;
